server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:moneytransfer
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
